# Site Settings (Custom variables accessible via {{ site.* }})
title: xkema.github.io
email: kemal.yilmaz@tutanota.com
description: xkema.github.io
url: ""

# Other Settings
permalink: /:year/:title
sass:
  style: compressed
  sourcemap: development

# Global Configuration
disable_disk_cache: true
ignore_theme_config: true
exclude:
  - package.json
  - package-lock.json
  - README.md
include:
  - _pages
timezone: Asia/Istanbul
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      category: "uncategorized"
      tags: "untagged"
  -
    scope:
      path: "_drafts"
      type: "posts"
    values:
      layout: "post"
      category: "uncategorized"
      tags: "untagged draft"
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

# Build Command Options
strict_front_matter: true
baseurl: ""