title: xkema.github.io
email: kemalxyz@gmail.com
description: welcome to xkema.github.io
permalink: /blog/:title
include:
  - _pages
# baseurl: /blog
sass:
  style: compressed
defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      category: "uncategorized"
      tags: "untagged"
