# Site Settings (Custom variables accessible via {{ site.* }})
title: "kemal yılmaz - blog"
email: kemal.yilmaz@tutanota.com
description: "A Front End Developer Blog - xkema.github.io"
url: ""

# Other Settings
permalink: /:year/:title
sass:
  style: compressed
  sourcemap: development

# Global Configuration
disable_disk_cache: true
ignore_theme_config: true
exclude:
  - package.json
  - package-lock.json
  - README.md
  - assets/raw
  - assets/tools
  - assets/favicons
include:
  - _pages
timezone: Asia/Istanbul
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      category: "uncategorized"
      tags: "untagged"
  -
    scope:
      path: "_drafts"
      type: "posts"
    values:
      layout: "post"
      category: "uncategorized"
      tags: "untagged draft"
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

# Build Command Options
strict_front_matter: true
baseurl: ""
# sitemap plugin configuration
url: "https://xkema.github.io"
plugins:
  - jekyll-sitemap